[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/seap-udea/MontuPython/blob/main/examples/MontuPython-TestCode.ipynb)

<p align="left"><img src="https://github.com/seap-udea/MontuPython/raw/main/montu/data/montu-python-logo-complete.webp" width="300" /></p>

In [26]:
# %pip install -Uq montu plotly
!mkdir -p ./gallery/

In [27]:
import numpy as np
import pandas as pd
import montu

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Salida helíaca de Sirio (Peret Sopedet)

Usamos `montu.HeliacalRise` del módulo `montu.phenomena` para predecir la primera mañana visible de Sirio alrededor de la tercera *apokatastasis* (139 d.C.) en Tebas. Cada modelo se prueba por separado.

Parámetros comunes del barrido: `scan_start` = 139-07-01, `scan_end` = 139-08-15, `k = 0.25` mag/masa de aire, magnitud límite al cénit 6.0.

In [28]:
third_apok = montu.load_historical_dates()['139-07-20']
third_apok

{'label': 'CE 139-07-20 — Third Apokatastasis',
 'description': 'Third <i>apokatastasis</i>: I-Akhet-1 coincides with the heliacal rise of Sopedet. Identified in the Latin work of Censorinus (Lull, p. 95).',
 'details': 'In CE 139, Censorinus described a coincidence of the civil New Year with Sirius’s heliacal rising — the third such return since the epoch used in modern reconstructions. His account is a rare Greco-Roman witness to Egyptian calendrical astronomy and remains a cornerstone for aligning pharaonic dates with the Julian calendar.',
 'source': 'Lull, J. (2020). La astronomía en el antiguo Egipto (Vol. 110). Universitat de València. p. 95 (Censorinus)',
 'egyptian_date': 'I-Akhet-1'}

In [29]:
Tebas = montu.Observer(lon=33, lat=24, height=0.075)
sirius = montu.Stars(subset='bright', ProperName='Sirius')

scan_start = montu.Time('139-07-01 00:00:00', calendar='mixed')
scan_end = montu.Time('140-08-15 00:00:00', calendar='mixed')

print('Observador:', Tebas)
print('Barrido:', scan_start.readable.datemix, '→', scan_end.readable.datemix)

Loading stellar catalogue montu_stellar_catalogue_v38_bright.csv
Observador: <montu.observer.Observer object at 0x113185350>
Barrido: 139-07-01 00:00:00 → 140-08-15 00:00:00

## Schaefer 1987 — depresión solar fija

Criterio operativo con Sol a −11° y masa de aire secante. Fuente: Schaefer (1987), *Archaeoastronomy* 11.

In [ ]:
calc_1987 = montu.HeliacalRise(
    model='schaefer1987',
    k=0.25,
    limiting_mag_zenith=6.0,
    sun_depression=-11.0,
)
rise_1987 = calc_1987.compute(sirius, Tebas, scan_start, scan_end)
calc_1987.print_rises(rise_1987, title='Schaefer 1987', body_label='Sirio')

## Schaefer 1985 — listado BASIC

Reconstrucción del programa publicado en *Sky & Telescope* 70, 261–263. Barrido matutino con brillo crepuscular y umbral fisiológico.

In [ ]:
calc_1985 = montu.HeliacalRise(
    model='schaefer1985',
    k=0.25,
    limiting_mag_zenith=6.0,
)
rise_1985 = calc_1985.compute(sirius, Tebas, scan_start, scan_end)
calc_1985.print_rises(rise_1985, title='Schaefer 1985 (BASIC)', body_label='Sirio')

## Belokrylov et al. 2011

Modelo empírico con extinción y corrección por cercanía al Sol. Fuente: *Bulgarian Astronomical Journal* 16, ecuaciones (4)–(8).

In [ ]:
calc_2011 = montu.HeliacalRise(
    model='belokrylov2011',
    k=0.25,
    reference_extinction=0.25,
)
rise_2011 = calc_2011.compute(sirius, Tebas, scan_start, scan_end)
calc_2011.print_rises(rise_2011, title='Belokrylov 2011', body_label='Sirio')

## Atajo con `heliacal_rise`

El wrapper calcula, imprime el resumen y devuelve el DataFrame.

In [ ]:
rise = montu.heliacal_rise(
    sirius, 
    Tebas, 
    scan_start, 
    scan_end,
    model='schaefer1987',
    k=0.25,
    limiting_mag_zenith=6.0,
    sun_depression=-11.0,
    title='Schaefer 1987',
    body_label='Sirio',
)

Schaefer 1987 — 2 date(s)
  [1] 139-07-20 00:00:00  04:28:38.194  Sirio 4.48°  Sun -11.00°
  [2] 140-07-19 00:00:00  04:28:28.906  Sirio 4.24°  Sun -11.00°
  source: Schaefer, B.E. 1987, Archaeoastronomy 11, S19–33; fixed solar depression with secant airmass and zenith limiting magnitude.

In [23]:
print(montu.Time(rise.day_jed[0], format='jd'))

Montu Time Object:
--------------------------
Readable:
    Date in proleptic UTC (.readable.datepro): 0139-07-19 00:00:00.000000
    Date in mixed UTC (.readable.datemix): 139-07-20 00:00:00
    Date in SPICE format (.readable.datespice): 0139 A.D. 07-19 00:00:00.00
    Date in caniucular format (.readable.datecan): hrw 2922-I-Akhet-1
    Weekday (.readable.weekday): 1 (sunday)
    Components (.readable.comps): [1, 139, 7, 19, 0, 0, 0, 0]
Objects:
    Date in datetime64 format (.readable.obj_datetime64): 0139-07-19T00:00:00.000000
    Date in PyPlanet Epoch (.obj_pyplanet): 1772027.5
    Date in PyEphem Epoch (.obj_pyephem): 139/7/20 00:00:00
General:
    Is bce (.bce): False
    Is Julian (.isjulian): True
Uniform scales:
    Terrestrial time:
        tt (.tt): -58710302782.8
        jtd (.jtd): 1772027.6066806
        htd (.htd): 1066530.1066806
    UTC time:
        et (.et): -58710312000.0
        jed (.jed): 1772027.5
        hed (.hed): 1066530.0
    Delta-t = TT - UTC (.deltat): 9217.2

In [27]:
rise = montu.heliacal_rise(
    sirius, 
    Tebas, 
    montu.Time('139-01-01', calendar='mixed'), 
    model='schaefer1987',
    k=0.25,
    limiting_mag_zenith=6.0,
    sun_depression=-11.0,
    title='Schaefer 1987',
    body_label='Sirio',
)

Schaefer 1987 — 1 date(s)
  [1] 139-07-20 00:00:00  04:28:38.194  0139-07-19 00:00:00.000000  hrw 2922-I-Akhet-1  Sirio 4.48°  Sun -11.00°
  source: Schaefer, B.E. 1987, Archaeoastronomy 11, S19–33; fixed solar depression with secant airmass and zenith limiting magnitude.

In [29]:
rise = montu.heliacal_rise(
    sirius, 
    montu.Observer(lon=32.6422, lat=25.6967, height=75/1000), 
    montu.Time('139-01-01', calendar='mixed'), 
    model='schaefer1987',
    k=0.25,
    limiting_mag_zenith=6.0,
    sun_depression=-11.0,
    title='Schaefer 1987',
    body_label='Sirio',
    )

Schaefer 1987 — 1 date(s)
  [1] 139-07-21 00:00:00  04:24:56.328  0139-07-20 00:00:00.000000  hrw 2922-I-Akhet-2  Sirio 3.96°  Sun -11.00°
  source: Schaefer, B.E. 1987, Archaeoastronomy 11, S19–33; fixed solar depression with secant airmass and zenith limiting magnitude.

In [35]:
# %pip install montu
"""Heliacal-rise calculation with MontuPython Desktop default values."""

import montu

# Default observer location in MontuPython Desktop: Giza, Egypt.
observer = montu.Observer(lon=31.1342, lat=29.9792, height=0.075)

# Default body and search interval: Sirius, 139 CE, mixed calendar, one year.
sirius = montu.Stars(subset="bright", ProperName="Sirius")
start = montu.Time("139-01-01", calendar="mixed")
end = start + 365 * montu.DAY

# Default Schaefer (1987) visibility model parameters.
calculator = montu.HeliacalRise(
    model="schaefer1987",
    k=0.25,
    limiting_mag_zenith=6.0,
    sun_depression=-11.0,
)

events = calculator.compute(sirius, observer, start, end)
calculator.print_rises(
    events,
    title="Heliacal rises of Sirius",
    body_label="Sirius",
)

Loading stellar catalogue montu_stellar_catalogue_v38_bright.csv
Heliacal rises of Sirius — 1 date(s)
  [1] 139-07-25 00:00:00  04:16:06.101  0139-07-24 00:00:00.000000  hrw 2922-I-Akhet-6  Sirius 3.91°  Sun -11.00°
  source: Schaefer, B.E. 1987, Archaeoastronomy 11, S19–33; fixed solar depression with secant airmass and zenith limiting magnitude.

In [ ]:
## Grid search — Schaefer 1987 y los tres Apokatastasis

Buscamos parámetros del modelo `schaefer1987` (`k`, `limiting_mag_zenith`, `sun_depression`) que produzcan la salida helíaca de Sirio en **I-Akhet-1** para las tres fechas históricas de *apokatastasis*, en el sitio indicado.

**Criterio de ajuste:** priorizar aciertos en caniucular `I-Akhet-1`, luego coincidencia exacta con la fecha histórica, y minimizar el desfase en días.

In [36]:
import time
from itertools import product

import numpy as np
import pandas as pd

# Sitio indicado para el ajuste (coordenadas del módulo Desktop / Giza).
Thebas = montu.Observer(lon=31.1342, lat=29.9792, height=0.075)
sirius = montu.Stars(subset='bright', ProperName='Sirius')

historical = montu.load_historical_dates()
APOKATASTASIS_KEYS = [
    'bce 2782-07-20',  # primera apokatastasis
    'bce 1322-07-20',  # segunda apokatastasis
    '139-07-20',       # tercera apokatastasis
]
APOKATASTASIS = [
    (key, historical[key]) for key in APOKATASTASIS_KEYS
]

SEARCH_BEFORE_DAYS = 90
SEARCH_AFTER_DAYS = 45


def first_heliacal_in_window(calculator, expected_key):
    """Primer heliacal rise detectado alrededor de la fecha histórica."""
    entry = historical[expected_key]
    expected = montu.Time(expected_key, calendar='mixed')
    start = expected - SEARCH_BEFORE_DAYS * montu.DAY
    end = expected + SEARCH_AFTER_DAYS * montu.DAY
    result = calculator.compute(sirius, Thebas, start, end)
    if result.empty:
        return {
            'historical_key': expected_key,
            'label': entry['label'],
            'expected_egyptian': entry['egyptian_date'],
            'detected_mixed': None,
            'detected_can': None,
            'day_error': np.nan,
            'akhet1_hit': False,
            'date_hit': False,
        }

    event = result.iloc[0]
    moment = montu.Time(event.day_jed, format='jd', calendar='mixed', full=True)
    day_error = abs(event.day_jed - expected.jed)
    detected_can = moment.readable.datecan
    return {
        'historical_key': expected_key,
        'label': entry['label'],
        'expected_egyptian': entry['egyptian_date'],
        'detected_mixed': moment.readable.datemix,
        'detected_can': detected_can,
        'day_error': day_error,
        'akhet1_hit': entry['egyptian_date'] in detected_can,
        'date_hit': day_error < 0.5,
        'local_time': event.local_time,
        'body_altitude_deg': event.body_altitude_deg,
        'sun_altitude_deg': event.sun_altitude_deg,
    }


def score_parameters(k, limiting_mag_zenith, sun_depression):
    calculator = montu.HeliacalRise(
        model='schaefer1987',
        k=float(k),
        limiting_mag_zenith=float(limiting_mag_zenith),
        sun_depression=float(sun_depression),
    )
    rows = [first_heliacal_in_window(calculator, key) for key, _ in APOKATASTASIS]
    akhet1_hits = sum(row['akhet1_hit'] for row in rows)
    date_hits = sum(row['date_hit'] for row in rows)
    total_day_error = float(np.nansum([row['day_error'] for row in rows]))
    score = akhet1_hits * 1000 + date_hits * 100 - total_day_error
    return {
        'k': float(k),
        'limiting_mag_zenith': float(limiting_mag_zenith),
        'sun_depression': float(sun_depression),
        'score': score,
        'akhet1_hits': akhet1_hits,
        'date_hits': date_hits,
        'total_day_error': total_day_error,
        'details': rows,
    }


def run_grid(k_values, lim_values, sun_values, label):
    started = time.perf_counter()
    rows = []
    total = len(k_values) * len(lim_values) * len(sun_values)
    for index, (k, lim, sun) in enumerate(product(k_values, lim_values, sun_values), start=1):
        rows.append(score_parameters(k, lim, sun))
        if index % max(1, total // 10) == 0:
            print(f'{label}: {index}/{total} combinaciones evaluadas …')
    df = pd.DataFrame(rows).sort_values(
        ['akhet1_hits', 'date_hits', 'total_day_error', 'score'],
        ascending=[False, False, True, False],
    )
    elapsed = time.perf_counter() - started
    print(f'{label} completado en {elapsed:.1f} s ({total} combinaciones).')
    return df


# --- Barrido grueso ---
coarse_k = np.arange(0.10, 0.55, 0.05)
coarse_lim = np.arange(3.5, 8.0, 0.5)
coarse_sun = np.arange(-16, -7, 1)

coarse_df = run_grid(coarse_k, coarse_lim, coarse_sun, 'Barrido grueso')
display(coarse_df.head(15))

best_coarse = coarse_df.iloc[0]
print('\nMejor combinación del barrido grueso:')
print(best_coarse[['k', 'limiting_mag_zenith', 'sun_depression', 'akhet1_hits', 'date_hits', 'total_day_error']])

# --- Refinamiento local alrededor del mejor punto ---
refine_k = np.arange(best_coarse.k - 0.05, best_coarse.k + 0.051, 0.01)
refine_lim = np.arange(best_coarse.limiting_mag_zenith - 0.5, best_coarse.limiting_mag_zenith + 0.51, 0.1)
refine_sun = np.arange(best_coarse.sun_depression - 1.0, best_coarse.sun_depression + 1.01, 0.25)

refined_df = run_grid(refine_k, refine_lim, refine_sun, 'Refinamiento')
display(refined_df.head(15))

best = refined_df.iloc[0]
print('\nMejor conjunto de parámetros encontrado:')
print(best[['k', 'limiting_mag_zenith', 'sun_depression', 'akhet1_hits', 'date_hits', 'total_day_error']])

verification_rows = []
for detail in best['details']:
    verification_rows.append({
        'Apokatastasis': detail['label'],
        'Fecha histórica': detail['historical_key'],
        'Esperado (caniucular)': detail['expected_egyptian'],
        'Detectado (mixed)': detail['detected_mixed'],
        'Detectado (caniucular)': detail['detected_can'],
        'Δ días': detail['day_error'],
        'I-Akhet-1': detail['akhet1_hit'],
        'Fecha exacta': detail['date_hit'],
    })

verification_df = pd.DataFrame(verification_rows)
display(verification_df)

print(
    f"\nResumen: {int(best.akhet1_hits)}/3 apokatastasis con I-Akhet-1; "
    f"{int(best.date_hits)}/3 con fecha histórica exacta."
)
if int(best.akhet1_hits) < 3:
    print(
        'Ningún conjunto del grid probado alcanzó I-Akhet-1 en las tres fechas '
        'con este observador y Schaefer 1987. El resultado anterior es el mejor compromiso.'
    )

Loading stellar catalogue montu_stellar_catalogue_v38_bright.csv
Barrido grueso: 72/729 combinaciones evaluadas …
Barrido grueso: 144/729 combinaciones evaluadas …
Barrido grueso: 216/729 combinaciones evaluadas …
Barrido grueso: 288/729 combinaciones evaluadas …
Barrido grueso: 360/729 combinaciones evaluadas …
Barrido grueso: 432/729 combinaciones evaluadas …
Barrido grueso: 504/729 combinaciones evaluadas …
Barrido grueso: 576/729 combinaciones evaluadas …
Barrido grueso: 648/729 combinaciones evaluadas …
Barrido grueso: 720/729 combinaciones evaluadas …
Barrido grueso completado en 187.9 s (729 combinaciones).

,k,limiting_mag_zenith,sun_depression,score,akhet1_hits,date_hits,total_day_error,details
261,0.25,4.5,-16.0,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
468,0.35,7.0,-16.0,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
631,0.45,7.0,-15.0,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
704,0.50,6.5,-14.0,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
162,0.20,3.5,-16.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
171,0.20,4.0,-16.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
244,0.25,3.5,-15.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
270,0.25,5.0,-16.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
279,0.25,5.5,-16.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
326,0.30,3.5,-14.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
343,0.30,4.5,-15.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
352,0.30,5.0,-15.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
360,0.30,5.5,-16.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
369,0.30,6.0,-16.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
378,0.30,6.5,-16.0,2076.999972,2,1,23.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."

Mejor combinación del barrido grueso:
k                           0.25
limiting_mag_zenith          4.5
sun_depression             -16.0
akhet1_hits                    2
date_hits                      1
total_day_error        22.000028
Name: 261, dtype: object
Refinamiento: 108/1089 combinaciones evaluadas …
Refinamiento: 216/1089 combinaciones evaluadas …
Refinamiento: 324/1089 combinaciones evaluadas …
Refinamiento: 432/1089 combinaciones evaluadas …
Refinamiento: 540/1089 combinaciones evaluadas …
Refinamiento: 648/1089 combinaciones evaluadas …
Refinamiento: 756/1089 combinaciones evaluadas …
Refinamiento: 864/1089 combinaciones evaluadas …
Refinamiento: 972/1089 combinaciones evaluadas …
Refinamiento: 1080/1089 combinaciones evaluadas …
Refinamiento completado en 273.7 s (1089 combinaciones).

,k,limiting_mag_zenith,sun_depression,score,akhet1_hits,date_hits,total_day_error,details
2,0.20,4.0,-16.50,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
11,0.20,4.1,-16.50,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
37,0.20,4.4,-16.75,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
46,0.20,4.5,-16.75,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
81,0.20,4.9,-17.00,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
90,0.20,5.0,-17.00,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
119,0.21,4.2,-16.50,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
128,0.21,4.3,-16.50,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
163,0.21,4.7,-16.75,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
172,0.21,4.8,-16.75,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
210,0.22,4.1,-16.25,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
219,0.22,4.2,-16.25,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
245,0.22,4.5,-16.50,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
254,0.22,4.6,-16.50,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."
289,0.22,5.0,-16.75,2077.999972,2,1,22.000028,"[{'historical_key': 'bce 2782-07-20', 'label':..."

Mejor conjunto de parámetros encontrado:
k                            0.2
limiting_mag_zenith          4.0
sun_depression             -16.5
akhet1_hits                    2
date_hits                      1
total_day_error        22.000028
Name: 2, dtype: object

,Apokatastasis,Fecha histórica,Esperado (caniucular),Detectado (mixed),Detectado (caniucular),Δ días,I-Akhet-1,Fecha exacta
0,BCE 2782-07-20 — First Apokatastasis,bce 2782-07-20,I-Akhet-1,-2781-07-31 00:00:00,hrw 0-I-Akhet-12,11.000000,True,False
1,BCE 1322-07-20 — Second Apokatastasis,bce 1322-07-20,I-Akhet-1,-1321-07-20 00:00:00,hrw 1461-I-Akhet-1,0.000000,True,True
2,CE 139-07-20 — Third Apokatastasis,139-07-20,I-Akhet-1,139-07-08 23:59:59,hrw 2921-IV-Shemu-24,11.000028,False,False

Resumen: 2/3 apokatastasis con I-Akhet-1; 1/3 con fecha histórica exacta.
Ningún conjunto del grid probado alcanzó I-Akhet-1 en las tres fechas con este observador y Schaefer 1987. El resultado anterior es el mejor compromiso.